### ISSUE TITLE
功能挺好，但这个必须依赖element-plus吗？

### ISSUE THREAD

**Issue by yumu7777777** [Liberty-liu/Everright-filter#3]

**Comment by Liberty-liu** [comment]
是的

**Comment by yumu7777777** [comment]
有考虑，不依赖第三方UI库吗




不许人间见白头
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liberty-liu/Everright-filter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月28日(星期五) 上午6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Liberty-liu/Everright-filter] 功能挺好，但这个必须依赖element-plus吗？ (Issue #3)





 
是的

**Comment by Liberty-liu** [comment]
有这种想过，但是不抱大腿工作量会很大，如果这个repo的功能对你有用，你可以考虑clone or fork，把内部依赖的element-plus组件按需引入，build的时候不排除，element-plus有这个功能的。

**Comment by Liberty-liu** [comment]
我尝试把这个加入进来，提供一个把element-plus打包在一起的一个文件

**Comment by yumu7777777** [comment]
大佬太强了

**Comment by Liberty-liu** [comment]
内部已经提供了一种包含element-plus的构建了，参照这里https://github.com/Liberty-liu/Everright-filter#explanation-of-the-different-builds
